// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jowkweemypfjdtuardfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvd2t3ZWVteXBmamR0dWFyZGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTczOTQsImV4cCI6MjA2NTU5MzM5NH0.XF0zmAdphuB8yvB1dpYCl70kx_lLaEaAIqY78e9KdtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);